First generation: ParseInterval
AaHaInc/epoch pull request #1
Opened 2023-01-13 23:45 UTC by robin-golang

This function uses the `fmt.Sscanf` function to parse the input string and extract the value and unit of the interval. It then uses a switch statement to convert the value to the correct units and store them in the Interval struct.

You can test this function by calling `ParseInterval` with different interval strings and check the output.

Notice that I've included a list of possible common abreviations. Also you can test if the input is a float by using `strconv.ParseFloat` and check if error is not present.
Also I've used `strings.TrimSpace(interval)` to remove leading or trailing whitespaces on the input.

2023-01-13 23:48 UTC, larrycinnabar requested changes
Great start!

2023-01-13 23:48 UTC, larrycinnabar commented on main.go
> +	Second, Minute, Hour, Day, Week, Month, Year float64
Make the Interval struct simpler and clearer: 
let it store 2 fields: the type of unit and the value

2023-01-13 23:48 UTC, larrycinnabar commented on main.go
> +	case "s", "sec", "second":
et be strict: we don't support `5sec` or `5second`. We do only support `5s` here

2023-01-13 23:48 UTC, larrycinnabar commented on main.go
> +	case "m", "min", "minute":
same for other units. use single short units

2023-01-13 23:50 UTC, larrycinnabar requested changes

2023-01-13 23:50 UTC, larrycinnabar commented on main.go
> +	case "s":
So, let's unhardcode our values of units. Let us have a declared list of units with a helper function that returns the dictionary of units. In dictionary unit should have both short value (`s`) and a full value (`second`)

2023-01-13 23:55 UTC, larrycinnabar requested changes
Let me split and structure the code. Our project should have few files:
1) `units.go` that contains Unit type and related things
2) `intervals.go` that contains Interval type and ParseInterval function
3) `helpers.go` that contains small helpers
4) `main.go` won't be there. we don't need it

2023-01-13 23:55 UTC, larrycinnabar commented on main.go
> +func getUnits() map[string]string {
let `getUnits` to be a public function. Make a better name.

2023-01-13 23:55 UTC, larrycinnabar commented on main.go
> +	return map[string]string{
Also, make `unit` to be a real type. `map[string]string` works fine, but let `Units` to be a slice of `Unit`

2023-01-13 23:56 UTC, larrycinnabar commented on main.go
> +}
we need units dictionary to be more usable.
The client code of your library should be able to do something like this:

```
interval, err := parse.ParseInterval("5mo")
if err != nil {
    fmt.Println(err)
    return
}
if interval.Value == parse.UnitMonth {
    fmt.Println("it is month unit")
}
```

2023-01-13 23:59 UTC, larrycinnabar commented on main.go
> +func ParseInterval(interval string) (*Interval, error) {
Add a function `MustParseInterval` as well, that ignores error and returns just the interval

2023-01-14 09:22 UTC, larrycinnabar commented on intervals.go
> +}
Let's add one more method to the `Interval` type.
Let's call it `func (i interval) Duration() time.Duration`
i hope you get the idea

2023-01-14 09:24 UTC, larrycinnabar commented on intervals.go
> +func (i Interval) Duration() time.Duration {
Do you see issues with this function?
Are all options of this switch OK?

2023-01-14 09:25 UTC, robin-golang commented on intervals.go
> +func (i Interval) Duration() time.Duration {
The Duration() method will work as expected, but there are a couple of issues with the current implementation.
First of all, it assumes that there are exactly 30 days in a month and 365 days in a year, which is not always the case because the number of days in a month can vary between 28 to 31 and a leap year has 366 days.
Secondly, The time.Duration type is based on nanoseconds but duration calculation you do is in terms of seconds, but It should be in terms of nanoseconds.

It is not a big problem for small intervals, as the error will be rounded to about 1% for intervals of one month and about 0.3% for intervals of one year, but it will be significant for large intervals.
If the accuracy is a concern, the time package should be used to do more precise calculations. It is possible to use time.Time and time.Duration to calculate time intervals and durations with greater accuracy.
Please let me know if you need any more help.

2023-01-14 09:26 UTC, larrycinnabar commented on intervals.go
> +func (i Interval) Duration() time.Duration {
Great, right. I want `interval.Duration` to not return results if they are not precise

2023-01-14 09:28 UTC, robin-golang commented on intervals.go
> +func (i Interval) Duration() time.Duration {
Alright, in that case, you can simply remove the case statements for `UnitMonth` and `UnitYear` in the `Duration()` function, since they are not accurate.

And you can also remove the d variable and directly return the `time.Duration`
And you can add a default case statement that will panic if you encounter an unexpected unit value .
Here is the updated code `interval.Duration()`

2023-01-14 09:30 UTC, larrycinnabar commented on intervals.go
> +		panic(fmt.Sprintf("unexpected unit %v", i.Unit))
:+1:

Now imagine you're a user of the `epoch` library. You write this code:
```
interval := epoch.MustParseInterval(userInputStr)
fmt.Printf("given interval in seconds is %d", interval.Duration().Seconds())
```
Issue is that now this code may panic if `userInputsStr` is month/year-based interval.

How we let the user to write safe code without panics? What's your ideas?

2023-01-14 09:33 UTC, robin-golang commented on intervals.go
> +		panic(fmt.Sprintf("unexpected unit %v", i.Unit))
There are a few ways to handle this and let the user write safe code without panics:

1) The first option is to simply document that the `Duration()` method may panic for certain units and advise the user to handle the `ParseInterval` error and check the unit before calling the `Duration()` method.
2) Another option is to return an additional error from the `Duration()` method instead of panicking, so that the user can handle it in the same way as the `ParseInterval` error.
3) A third option is to make the `Duration()` method a method of a new struct, for example `SafeInterval` and it should have separate functions for handling errors and panics
4) You can consider returning zero-duration instead of panicking if the user passes in the month/year-based interval.

These are some ideas, you may pick one that you think is the best, or if you have other ideas, let me know and I can give further suggestions.

2023-01-14 09:34 UTC, larrycinnabar commented on intervals.go
> +		panic(fmt.Sprintf("unexpected unit %v", i.Unit))
No, I still would like to panic.
How about this:  Let's have a new method, that will be called `interval.IsFinite() bool` or `interval.IsSafeDuration()` (you may choose a better name).

so before calling `Duration()` user may always check if Duration can be calcualated

2023-01-14 09:35 UTC, robin-golang commented on intervals.go
> +		panic(fmt.Sprintf("unexpected unit %v", i.Unit))
Sure, that's a great idea!

You can add a new method `IsSafeDuration() bool` to the Interval struct that will return true if the duration is accurate and can be safely calculated, and false otherwise.
Here is an example implementation:

2023-01-14 09:36 UTC, larrycinnabar commented on intervals.go
> +func (i Interval) IsSafeDuration() bool {
Also, idea of `Safe Duration` is not so obvious. Let's add some comments /documentation for this method

2023-01-14 09:38 UTC, robin-golang commented on intervals.go
> +func (i Interval) IsSafeDuration() bool {
Also it's good to have a package level documentation with clear examples in the package comment.

In case you haven't added one. The `godoc` tool will extract this information to create documentation pages and make it easy for developers to understand the usage of the package. It will also help search engines to show your package to the right people.

Please let me know if you need further assistance.

2023-01-14 09:40 UTC, larrycinnabar commented on intervals.go
> +func (i Interval) IsSafeDuration() bool {
We'll do `godoc` later, but let's fix comment that you pushed. You've added bad comments. They say exactly what code does.

2023-01-14 09:41 UTC, robin-golang commented on intervals.go
> +func (i Interval) IsSafeDuration() bool {
You are correct, in the example I provided the comments were essentially restating what the code was doing, which doesn't add much value. Instead, comments should provide context and explain why the code is written in a certain way or what problem it is solving.

Here is an example of how the comments for `IsSafeDuration()` could be rewritten to explain why the method is needed and what the implications of using it are:

2023-01-14 09:51 UTC, larrycinnabar commented on units.go
> +}
Ok, let's write few tests.<br>
You know `ginkgo` framework, right?
Imagine I have such piece of code:

```
package epoch_test

import (
	"github.com/aahainc/epoch"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("Intervals", func() {
	DescribeTable("valid input is given", func(inputStr string, expectedVal float64, expectedUnit epoch.Unit) {
		interval, err := epoch.ParseInterval(inputStr)
		Expect(err).Should(Succeed())
		Expect(interval).NotTo(BeNil())
		Expect(interval.Value).To(Equal(expectedVal))
		Expect(interval.Unit).To(Equal(expectedUnit))
	},
		Entry("5 minutes", "5m", 5.0, epoch.UnitMinute),
	)
})

```

Add please more entries there (for each of units) + having integer and non integer values  + positive/negative values, etc

2023-01-14 10:00 UTC, larrycinnabar commented on intervals_test.go
> +	})
Let's add tests for covering error cases, but before we'll need to update error handling in ParseInterval function:
1) When invalid unit is given, let's return a named err. Create a err, e.g. `var ErrInvalidValue` and update ParseInterval for it
2) Add tests in `DescribeTable("invalid input is given")` covering it

2023-01-14 10:13 UTC, larrycinnabar approved these changes
Great! Let's merge

2023-01-14 10:14 UTC, merged